server:
  port: 7081
spring:
  elasticsearch:
    uris: http://localhost:9200
    username: elastic
    password: changeme
#  data:
#    elasticsearch:
#      client:
#        rest:
#          uris: "http://localhost:9200"  # Địa chỉ Elasticsearch
#          username: "elastic"         # Tên người dùng Elasticsearch
#          password: "changeme"      # Mật khẩu Elasticsearch
#      repositories:
#        enabled: true
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update

    database-platform:
      org.hibernate.dialect.MySQLDialect
    show-sql:
      false

  datasource:
    driver-class-name:
      com.mysql.cj.jdbc.Driver
  batch:
    job:
      enabled:
        false
    jdbc:
      initialize-schema:
        ALWAYS
  main:
    allow-bean-definition-overriding:
      true